### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by idajimenez** [Frosty92/react-native-audio-android#1]
Hi! I am trying to use this package but this error showed when running react-native run-android.
`/node_modules/react-native-audio-android/android/src/main/java/com/frosty92/RCTAudioRecorder/RCTAudioRecorder.java:29: error: cannot find symbol
     private Promise audioRecorderPromise = null;
             ^
  symbol:   class Promise
  location: class RCTAudioRecorder`

Hoping you can check on it. Thanks

**Comment by Frosty92** [comment]
Hello, 

You are getting this error because the class `Promise` is not available. This class is imported from 'com.facebook.react.bridge', and is only available on `react-native` 0.15 and above. Which version of react-native are you using?

**Comment by Frosty92** [comment]
In any case, I rewrote the code to make it compatible with lower react versions. If you run the latest version (`npm uninstall react-native-audio-android` then `npm install react-native-audio-android`) you should not have this error (: 

P.S: check out the Readme, it has been updated!

**Comment by idajimenez** [comment]
I am running it on react-native 0.25.1. I'll try that. Thanks

**Comment by idajimenez** [comment]
Thanks! It's running properly now but when I use your code for basic usage, it returns 
`Cannot read property 'then' of undefined` and `errorCallback is not a function`

**Comment by Frosty92** [comment]
Yes, the readme didn't get updated. Try the code in Usage now, it should work;third time's the charm.

**Comment by idajimenez** [comment]
Thank you for your help! It's working now.
